# Generated by Django 4.2.13 on 2025-01-02 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mac_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("units", models.CharField(max_length=255)),
                ("price_per_unit", models.FloatField()),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
