# Generated by Django 4.2.13 on 2025-01-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_providercompanies"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicedetail",
            name="provider_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.providercompanies",
            ),
        ),
    ]
