# Generated by Django 4.2.13 on 2025-01-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_devicedetail_provider_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicedetail",
            name="provider_company",
        ),
        migrations.AddField(
            model_name="devicedetail",
            name="provider_type",
            field=models.CharField(
                choices=[("ISP", "ISP"), ("Camera Connection", "Camera Connection")],
                default=1,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="providercompanies",
            name="provider_type",
            field=models.CharField(
                choices=[("ISP", "ISP"), ("Camera Connection", "Camera Connection")],
                max_length=255,
            ),
        ),
    ]
