# Generated by Django 4.2.13 on 2024-12-24 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(default="0", max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="date_joined",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
