# Generated by Django 4.2.13 on 2025-01-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customer_customer_id_customer_date_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("install_amount", models.FloatField()),
                ("bill_amount", models.FloatField()),
                ("cable_amount", models.FloatField()),
                ("payment_recieved", models.FloatField()),
                ("balance", models.FloatField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.customer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_type", models.CharField(blank=True, max_length=255, null=True)),
                ("activation_date", models.DateField(blank=True, null=True)),
                ("isp_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.customer",
                    ),
                ),
            ],
        ),
    ]
