# Generated by Django 4.2.13 on 2025-01-02 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("users", "0004_payment_additionaldata"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="devices",
            field=models.ManyToManyField(
                blank=True, null=True, to="inventory.devicedetail"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.partner",
            ),
        ),
    ]
