# Generated by Django 4.2.13 on 2025-01-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_attacheddevice"),
        ("users", "0005_customer_devices_customer_partner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionaldata",
            name="isp_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ION", "ION"),
                    ("Alliance Broadband", "Alliance Broadband"),
                    ("BSNL", "BSNL"),
                    ("Other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="devices",
            field=models.ManyToManyField(
                blank=True, null=True, to="inventory.attacheddevice"
            ),
        ),
    ]
