# Generated by Django 4.2.13 on 2025-01-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_attacheddevice"),
        ("users", "0007_alter_customer_devices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="devices",
            field=models.ManyToManyField(
                blank=True, null=True, to="inventory.attacheddevice"
            ),
        ),
    ]
