# Generated by Django 4.2.13 on 2025-01-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_newconnectionrequest_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="newconnectionrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("New Internet Connection", "New Internet Connection"),
                    ("Camera Connection", "Camera Connection"),
                    ("Other", "Other"),
                ],
                default="New Internet Connection",
                max_length=255,
            ),
        ),
    ]
